FROM python:3.12-slim AS backend

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y \
    gcc g++ build-essential python3-dev libpq-dev
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
