FROM python:3.12-slim AS celery_worker

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y \
    gcc g++ build-essential python3-dev libpq-dev
RUN pip install --no-cache-dir -r requirements.txt

CMD ["celery", "-A", "app.utils.celery.celery", "worker", "--loglevel=info", "--pool=solo"]
