FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app


RUN apt-get update && apt-get install -y \
    gcc g++ build-essential python3-dev libpq-dev


COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
