"""change relation

Revision ID: 352b6339beca
Revises: ed1aa62e1565
Create Date: 2025-01-26 17:11:24.896787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352b6339beca'
down_revision: Union[str, None] = 'ed1aa62e1565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_film_library_films_id', table_name='user_film_library')
    op.drop_index('ix_user_film_library_users_id', table_name='user_film_library')
    op.drop_table('user_film_library')
    op.drop_index('ix_film_director_director_id', table_name='film_director')
    op.drop_index('ix_film_director_film_id', table_name='film_director')
    op.drop_table('film_director')
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('film_director',
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('director_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], name='film_director_director_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name='film_director_film_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('film_id', 'director_id', name='film_director_pkey')
    )
    op.create_index('ix_film_director_film_id', 'film_director', ['film_id'], unique=False)
    op.create_index('ix_film_director_director_id', 'film_director', ['director_id'], unique=False)
    op.create_table('user_film_library',
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('films_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['films_id'], ['films.id'], name='user_film_library_films_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='user_film_library_users_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('users_id', 'films_id', name='user_film_library_pkey')
    )
    op.create_index('ix_user_film_library_users_id', 'user_film_library', ['users_id'], unique=False)
    op.create_index('ix_user_film_library_films_id', 'user_film_library', ['films_id'], unique=False)
    # ### end Alembic commands ###
