"""add film and user relationship

Revision ID: ed1aa62e1565
Revises: 60dc2709f0e4
Create Date: 2025-01-26 16:27:16.907188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1aa62e1565'
down_revision: Union[str, None] = '60dc2709f0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_film_library',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('films_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['films_id'], ['films.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('users_id', 'films_id')
    )
    op.create_index(op.f('ix_user_film_library_films_id'), 'user_film_library', ['films_id'], unique=False)
    op.create_index(op.f('ix_user_film_library_users_id'), 'user_film_library', ['users_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_film_library_users_id'), table_name='user_film_library')
    op.drop_index(op.f('ix_user_film_library_films_id'), table_name='user_film_library')
    op.drop_table('user_film_library')
    # ### end Alembic commands ###
